version: '3'
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: User@123
      MYSQL_DATABASE: usermanager
      MYSQL_USER: root
      MYSQL_PASSWORD: User@123
    networks:
      - docker-network
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: User@123 
    networks:
      - docker-network
  #production_nginx
  production_nginx: 
    build: ./production-site
    ports:
      - "8000:80"
networks:
  docker-network:
volumes:
  db_data: